#exclude: ^(docs|tests/files|tasks.py)

ci:
  autoupdate_schedule: monthly
  #skip: [mypy, pyright]
  autofix_commit_msg: pre-commit auto-fixes
  autoupdate_commit_msg: pre-commit autoupdate

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=100']  # 1000 KB = 1 MB

  #- repo: https://github.com/astral-sh/ruff-pre-commit
  #  rev: v0.11.12
  #  hooks:
  #    - id: ruff
  #      args: [--fix, --unsafe-fixes]
  #    - id: ruff-format

  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: v1.16.0
  #  hooks:
  #    - id: mypy
  #      #additional_dependencies: [numpy>=1.2.5]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        stages: [pre-commit, commit-msg]
        exclude_types: [html]
        args: [--ignore-words=.codespell.ignore]
        #additional_dependencies: [tomli] # needed to read pyproject.toml below py3.11
        #exclude: src/pymatgen/analysis/aflow_prototypes.json

  #- repo: https://github.com/adamchainz/blacken-docs
  #  rev: 1.19.1
  #  hooks:
  #    - id: blacken-docs

  #- repo: https://github.com/pycqa/flake8
  #  rev: 7.1.0
  #  hooks:
  #  -   id: flake8
  #  additional_dependencies: ['flake8-docstrings']

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        # MD013: line too long
        # MD024: Multiple headings with the same content
        # MD033: no inline HTML
        # MD041: first line in a file should be a top-level heading
        # MD025: single title
        args: [--disable, MD013, MD024, MD025, MD033, MD041, "--"]

  #- repo: https://github.com/RobertCraigie/pyright-python
  #  rev: v1.1.401
  #  hooks:
  #    - id: pyright

  #- repo: https://github.com/PyCQA/doc8
  #  rev: 2.0.0
  #  hooks:
  #    - id: doc8
  #      args: [--max-line-length=120]

  - repo: local
    hooks:
      - id: check-build-config
        name: Run check-build-config
        entry: python abichecks/scripts/check-build-config.py
        language: python
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/check-config-h.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/check-forbidden-flags.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/check_ascii.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/warningschk.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/abirules_tools.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/check-build-examples.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/check-conflict-markers.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/check-libpaw.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/check_forbidden.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/check-binaries-conf.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/check-build-refs.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/check-cpp-options.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/check-line-lengths.py
      #- id: run-modified-tests
      #  name: Run pytest on modified files
      #  entry: python abichecks/scripts/check_inlined_macros.py
